   # Projeto 1

## 1ª Tarefa :

Primeiramente irei importar os dicionarios que serão utilizados no decorrer do projeto, como o pandas (pd) e o numpy (np).

In [2]:
import pandas as pd

Passo a passo:

1- Fiz o Dowload do datatran2019 e datatran2020, retirei o zip, transformando em cvs e depois os coloquei em repositorio no meu github, para transformar em um link, assim o código poderá ser aberto em qualquer máquina.

2- Importei os aquirvos como DataFrames.

3- O erro (ParserError: Error tokenizing data. C error: Expected 3 fields in line 3, saw 4) apareceu para o datatran2019.csv e datatran2020.csv. Pesquisei pela internet e achei a solução, a qual modifica o modo de separar as colunas.

4- Apos o passo 3 o erro (UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 22: invalid continuation byte) apareceu para o datatran2019.csv e datatran2020.csv, para soluciona-lo tambem procurei na internet para achar a solução, a qual corrige a codificação do arquivo.

In [3]:
df1 = pd.read_csv('https://raw.githubusercontent.com/Hermano-Neto/datatran/main/datatran2019.csv',  sep = ';', encoding = 'latin-1')
df1

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,182210.0,2019-01-01,terça-feira,01:30:00,SP,116.0,218,GUARULHOS,Falta de Atenção à Condução,Colisão com objeto estático,...,0,0,0,4,1,"-23,46052014","-46,48772478",SR-SP,DEL6/1,UOP01/SP
1,182211.0,2019-01-01,terça-feira,01:30:00,PR,373.0,"177,3",PONTA GROSSA,Falta de Atenção à Condução,Colisão traseira,...,0,0,0,1,1,"-25,05533957","-50,22776753",SR-PR,DEL7/3,UOP01/PR
2,182212.0,2019-01-01,terça-feira,00:45:00,SC,101.0,16,GARUVA,Animais na Pista,Colisão com objeto estático,...,0,0,0,1,1,"-26,1216","-48,8826",SR-SC,DEL8/3,UOP01/SC
3,182214.0,2019-01-01,terça-feira,00:00:00,CE,20.0,"429,5",FORTALEZA,Ingestão de Substâncias Psicoativas,Colisão com objeto estático,...,1,0,0,1,1,"-3,76999","-38,670063",SR-CE,DEL16/1,UOP02/CE
4,182215.0,2019-01-01,terça-feira,01:00:00,MG,381.0,327,NOVA ERA,Falta de Atenção à Condução,Colisão transversal,...,1,1,0,1,2,"-19,7609","-43,0306",SR-MG,DEL4/3,UOP01/MG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67441,266255.0,2019-10-07,segunda-feira,09:10:00,ES,101.0,"270,5",SERRA,Falta de Atenção à Condução,Tombamento,...,1,1,0,1,2,"-20,23107","-40,27387",SR-ES,DEL12/2,UOP01/ES
67442,266406.0,2019-11-25,segunda-feira,07:20:00,PR,116.0,125,FAZENDA RIO GRANDE,Falta de Atenção à Condução,Colisão lateral,...,0,1,1,1,2,"-25,59505","-49,31631",SR-PR,DEL7/1,UOP03/PR
67443,266434.0,2019-06-03,segunda-feira,19:00:00,CE,222.0,"1,4",CAUCAIA,Não guardar distância de segurança,Colisão traseira,...,1,1,0,1,2,"-3,736507","-38,65337",SR-CE,DEL16/1,UOP01/CE
67444,266573.0,2019-07-13,sábado,19:35:00,PR,373.0,425,CANDOI,Defeito Mecânico no Veículo,Saída de leito carroçável,...,1,0,0,1,1,"-25,7118","-52,18374",SR-PR,DEL7/3,UOP02/PR
67445,266627.0,2019-10-22,terça-feira,20:20:00,BA,324.0,608,SIMOES FILHO,Defeito na Via,Queda de ocupante de veículo,...,0,0,0,1,1,"-12,78156","-38,41656",SR-BA,DEL10/1,UOP01/BA

In [3]:
df2 = pd.read_csv('https://raw.githubusercontent.com/Hermano-Neto/datatran/main/datatran2020.csv', sep = ';', encoding = 'latin-1')
df2

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,260031.0,2020-01-01,quarta-feira,01:00:00,TO,153.0,"678,1",GURUPI,Animais na Pista,Atropelamento de Animal,...,5,0,0,5,1,"-11,77460203","-49,10744996",SR-TO,UOP01/TO,NaN
1,260036.0,2020-01-01,quarta-feira,01:00:00,RJ,116.0,178,NOVA IGUACU,Falta de Atenção do Pedestre,Atropelamento de Pedestre,...,0,1,0,0,1,"-22,75223028","-43,4379103",SR-RJ,DEL5/1,UOP02/RJ
2,260037.0,2020-01-01,quarta-feira,01:52:00,SC,101.0,"206,9",SAO JOSE,Ingestão de Álcool,Colisão lateral,...,0,1,0,1,2,"-27,59193546","-48,61824557",SR-SC,DEL8/1,UOP01/SC
3,260038.0,2020-01-01,quarta-feira,01:15:00,RO,364.0,236,CACOAL,Velocidade Incompatível,Saída de leito carroçável,...,1,0,0,1,1,"-11,44624577","-61,43761218",SR-RO,DEL21/2,UOP02/RO
4,260039.0,2020-01-01,quarta-feira,01:30:00,PR,153.0,360,REBOUCAS,Ingestão de Álcool,Capotamento,...,4,0,0,6,1,"-25,67503796","-50,75089805",SR-PR,DEL7/3,UOP04/PR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63442,334713.0,2020-12-23,quarta-feira,13:58:00,PA,316.0,62,CASTANHAL,Ingestão de Álcool,Colisão traseira,...,0,2,0,1,2,"-1,29786885","-47,93764104",SR-PA,UOP01,DEL01
63443,334777.0,2020-12-19,sábado,23:00:00,PA,316.0,106,SANTA MARIA DO PARA,Desobediência às normas de trânsito pelo condutor,Colisão frontal,...,0,1,0,1,2,"-1,34101996","-47,55122901",SR-PA,UOP02,DEL01
63444,334780.0,2020-12-08,terça-feira,06:10:00,PR,116.0,"90,9",PIRAQUARA,Condutor Dormindo,Colisão traseira,...,0,1,0,2,2,"-25,4611174","-49,08880123",SR-PR,UOP01,DEL01
63445,334788.0,2020-12-31,quinta-feira,22:30:00,SC,101.0,"146,9",ITAPEMA,Avarias e/ou desgaste excessivo no pneu,Colisão com objeto,...,0,0,0,0,1,"-27,09129094","-48,61669064",SR-SC,UOP03,DEL04
63446,334959.0,2020-11-18,quarta-feira,18:00:00,AL,104.0,"90,3",RIO LARGO,Falta de Atenção do Pedestre,Atropelamento de Pedestre,...,2,0,0,2,1,"-9,50059087","-35,81127569",SR-AL,UOP01,DEL01

## 2ª Tarefa :

### a) Quantos acidentes ocorreram em cada ano?

passo a passo:

1- Verifiquei a quantidade de index(linhas) utilizando o metodo len().

2- Juntei os anos e suas respectivas quantidades de linhas e fiz um novo dataframe, colocando os anos como linhas e o número de acidentes como colunas.

3- Dei um nome para as linhas, para ficar mais claro o que cada linha representa.

In [4]:
acidente1 = len(df1.index)
acidente2 = len(df2.index)

df_2a = pd.DataFrame({'Num. de acidentes': [acidente1, acidente2]
                    }, index = ['2019', '2020'])

df_2a.index.names = ['Anos']
df_2a

      Num. de acidentes
Anos
2019              67446
2020              63447

Também se pode responder apenas observando o output de cada um, onde rows representa as linhas, dando o mesmo resultado para cada um deles, 2019 com 67446 acidentes e 2020 com 63447 acidentes.

### b) quantas variáveis cada conjunto de dados registra?

passo a passo:

1- Verifiquei a quantidade de columns(colunas ou variáveis) utilizando o metodo len().

2- Juntei os anos e suas respectivas quantidades de variáveis e fiz um novo dataframe, colocando os anos como linhas e o número de variáveis como colunas.

3- Dei um nome para as linhas, para ficar mais claro o que cada linha representa.

In [5]:
var1 = len(df1.columns)
var2 = len(df2.columns)

df_2b = pd.df_a = pd.DataFrame({'Num. de variáveis': [var1, var2]
                              }, index = ['2019', '2020'])

df_2b.index.names = ['Anos']
df_2b

      Num. de variáveis
Anos
2019                 30
2020                 30

Também se pode responder observando o output de cada um, onde Columns representa as colunas, dando o mesmo resultado para cada um deles, 2019 com 30 variáveis e 2020 com 30 variáveis.

### c) quais as cinco cidades brasileiras onde mais ocorreram acidentes em rodovias federais?

passo a passo:

1- Procurei na internet algum método que me auxiliasse a contar a quantidade de vezes que x cidade aparece, apos a contagem ele cria uma series contendo o nome de cada cidade e a quantidade de vezes que ela aparece no dataframe.
    
2- Criei uma lista para cada ano e inseri as 5 primeiras cidades, que são as com a maior quantidade de acidentes.

3- Criei um dataframe com multiindex para inserir o ano de 2019 e 2020 dentro dele, para colocar todos os dados dentro de apenas um dataframe. Para isso tive que criar uma unica coluna 'Cidades' que contem 10 dados(5 de 2019 e 5 de 2020). Após isso, inseri dois indices, o 1º contendo os anos(10 dados) e o 2º as colocações(10 dados). Fica notório que cada um deles recebe 10 dados e o mesmo padrão, pois caso seja inserido um valor a mais ou a menos em um deles o código dará errado.

4- Para ficar ainda mais organizado coloquei nomes em cada index, tornando muito mais compreensivel o dataframe.

In [6]:
cidades1 = df1['municipio'].value_counts()
l1_2c = []

cidades2 = df2['municipio'].value_counts()
l2_2c = []

for i in range(0, 5):
    l1_2c.append(cidades1.index[i])
    l2_2c.append(cidades2.index[i])

df_2c = pd.DataFrame({'Cidade': [l1_2c[0], l1_2c[1], l1_2c[2], l1_2c[3], l1_2c[4], l2_2c[0], l2_2c[1], l2_2c[2], l2_2c[3], l2_2c[4]]},
                    index = [['2019', '2019', '2019', '2019', '2019','2020', '2020', '2020', '2020', '2020'],
                    ['1º', '2º', '3º', '4º', '5º','1º', '2º', '3º', '4º', '5º']]
                    )

df_2c.index.names = ['Ano', 'Colocação']
df_2c

                   Cidade
Ano  Colocação
2019 1º          CURITIBA
     2º          BRASILIA
     3º          SAO JOSE
     4º         GUARULHOS
     5º             SERRA
2020 1º          BRASILIA
     2º          CURITIBA
     3º         GUARULHOS
     4º          SAO JOSE
     5º           PALHOCA

### d) quantos acidentes com feridos graves aconteceram na Paraíba em 2019?

passo a passo: 

1- Criei uma series em que fosse atribuido apenas a parte necessária para a questão, para facilitar o processo. O novo1 recebeu seu dataframe especificando a linha e coluna necessária, sendo na linha especificando que eu queria 'PB' da coluna 'uf', onde procuraria apenas no 'PB' de cada linha. Já na coluna especifiquei apenas o 'feridos_graves', para assim criar uma series que possuisse os valores de feridos graves na Paraíba.

2- Depois eu atualizei a series para pegar apenas valores maiores que 0, que seriam aqueles q ocorreram feridos graves no acidente.  

OBS.: foi necessário separar o passo 1 do 2, pois dava um erro junto a saída, apesar de funcionar perfeitamente.

4-Printei a saída, a qual mostra a quantidade de acidentes com feridos graves na PB em 2019.

In [7]:
novo1 = df1[df1.uf == 'PB'] ['feridos_graves']
novo1 = novo1[novo1 >= 1]

df_2d = pd.DataFrame({'Acidentes com feridos graves': len(novo1)},
                    index = ['2019'])
df_2d.index.names = ['Ano']
df_2d

      Acidentes com feridos graves
Ano
2019                           414

## 3ª Tarefa

### a) ranking de acidentes por estado para ambos os anos (um só arquivo combinando a informação dos dois anos)

passo a passo:

1- contei a quantidade de vezes que cada estado apareceu na coluna uf, atribuindo a uma series.

2- Somei a series de 2019 e 2020 para fazer uma series unica que combine os 2.

3- Transformei a series soma em um dataframe organizando os valores de maior para menor da coluna uf.

4- Modifiquei o nome da coluna e linha para a correta e depois transformei o dataframe em um arquivo csv.

In [8]:
novo1_3a = df1['uf'].value_counts()
novo2_3a = df2['uf'].value_counts()
soma = novo1_3a + novo2_3a

df_3a = pd.DataFrame(soma).sort_values(by = 'uf', ascending=False)
df_3a.columns = ['2019-2020']
df_3a.index.names = ['uf']
df_3a.to_csv()

'uf,2019-2020\r\nMG,17083\r\nSC,15645\r\nPR,14876\r\nRJ,8828\r\nRS,8771\r\nSP,8417\r\nBA,6914\r\nGO,6580\r\nES,5372\r\nPE,5293\r\nMT,4326\r\nCE,3263\r\nRO,3018\r\nMS,2974\r\nPB,2965\r\nRN,2770\r\nPI,2546\r\nMA,2226\r\nDF,2130\r\nPA,1776\r\nAL,1257\r\nSE,1186\r\nTO,1115\r\nAC,554\r\nRR,487\r\nAP,283\r\nAM,238\r\n'

### b) acidentes por dia da semana para ambos os anos (um só arquivo combinando a informação dos dois anos).

passo a passo:

OBS.: mesmos passos da questãoa cima.

1- contei a quantidade de vezes que cada dia da semana apareceu na coluna dia_semana, atribuindo a uma series.

2- Somei a series de 2019 e 2020 para fazer uma series unica que combine os 2.

3- Transformei a series soma em um dataframe organizando os valores de maior para menor da coluna uf.

4- Modifiquei o nome da coluna e linha para a correta e depois transformei o dataframe em um arquivo csv.

In [9]:
novo1_3b = df1['dia_semana'].value_counts()
novo2_3b = df2['dia_semana'].value_counts()

soma = novo1_3b + novo2_3b

df_3a = pd.DataFrame(soma).sort_values(by = 'dia_semana', ascending=False)
df_3a.columns = ['2019-2020']
df_3a.index.names = ['dia_semana']
df_3a.to_csv()
df_3a

               2019-2020
dia_semana
sábado             21744
domingo            21706
sexta-feira        20131
segunda-feira      17638
quinta-feira       16981
quarta-feira       16516
terça-feira        16177

## 4ª Tarefa

### a) qual a causa mais frequente e a mais rara de acidentes registrados nos dois anos?

passo a passo:

1- Utilizei o mesmo metodo que aprendi na letra C da 2ª tarefa(value_counts()).

2- Criei uma lista para cada ano para inserir o mais frequente e o(s) mais raro(s) caso(s) de acidentes. Os coloquei utilizando o append, o qual apenas coloca o valor ou termo que estiver dentro do ().

3- No ano de 2020 tiveram mais de uma causa rara, entçao tive que criar um metodo que colocassem todos dentro da lista. Este método consiste em uma repetição, a qual verifica se a quantidade de acidentes x é igual ao de y, se for igual ele pegara o valor y e ira inserir na lista, se não, irá parar a repetição.

4- Criei um dataframe que contem as causas mais raras e frequentes de 2019 e 2020, utilizando o mesmo método da 2ª tarefa letra C.

In [10]:
causa1 = df1['causa_acidente'].value_counts()
l1_4a = [] 
        
l1_4a.append(causa1.index[0])
l1_4a.append(causa1.index[-1])
l1_4a

['Falta de Atenção à Condução', 'Ingestão de Substâncias Psicoativas']

In [11]:
causa2 = df2['causa_acidente'].value_counts()
l2_4a = []

l2_4a.append(causa2.index[0])
l2_4a.append(causa2.index[-1])

c = -1
while True:
    if causa2[c] == causa2[c - 1]:
        l2_4a.append(causa2.index[c - 1])   
        c -= 1
        
    else:
        break
l2_4a

['Falta de Atenção à Condução',
 'Trafegar com motocicleta (ou similar) entre as faixas',
 'Acumulo de óleo sobre o pavimento',
 'Ausência de sinalização',
 'Acumulo de água sobre o pavimento',
 'Condutor usando celular',
 'Ingestão de álcool ou de substâncias psicoativas pelo pedestre',
 'Pedestre cruzava a pista fora da faixa',
 'Afundamento ou ondulação no pavimento',
 'Frear bruscamente',
 'Acostamento em desnível']

In [12]:
df_4a = pd.DataFrame({'Causa do acidente': [l1_4a[1], l2_4a[1], l2_4a[2], l2_4a[3], l2_4a[4], l2_4a[5], l2_4a[6], l2_4a[7], l2_4a[8],
                                l2_4a[9], l2_4a[10]]},
                     index = [['2019', '2020', '2019', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020'],
                              ['mais frequente', 'mais frequente', 'mais rara', 'mais rara', 'mais rara', 'mais rara',
                               'mais rara', 'mais rara', 'mais rara', 'mais rara', 'mais rara']])

df_4a.index.names = ['Ano', 'Classificação']
df_4a

                                                     Causa do acidente
Ano  Classificação
2019 mais frequente                Ingestão de Substâncias Psicoativas
2020 mais frequente  Trafegar com motocicleta (ou similar) entre as...
2019 mais rara                       Acumulo de óleo sobre o pavimento
2020 mais rara                                 Ausência de sinalização
     mais rara                       Acumulo de água sobre o pavimento
     mais rara                                 Condutor usando celular
     mais rara       Ingestão de álcool ou de substâncias psicoativ...
     mais rara                  Pedestre cruzava a pista fora da faixa
     mais rara                   Afundamento ou ondulação no pavimento
     mais rara                                       Frear bruscamente
     mais rara                                 Acostamento em desnível

### b) qual a proporção de pessoas ilesas e de feridos graves por mês em cada um dos anos considerados? (proporção = numero de ilesos ou feridos graves/ número total de pessoas envolvidas no acidente)

passo a passo:

1- Primeiramente chamei as colunas para saber como estavam escritas no dataframe e chama-las corretamente.

2- Depois atribui a soma de todos os integrantes de 'ilesos', 'feridos_graves' e 'pessoas' à variaveis, para deixar o código mais limpo e visível.

3- Por fim, fiz a proporção e porcentagem para os ilesos e os feridos graves e os coloquei dentro de um dataframe.

In [13]:
df1.columns

Index(['id', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km',
       'municipio', 'causa_acidente', 'tipo_acidente',
       'classificacao_acidente', 'fase_dia', 'sentido_via',
       'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo',
       'pessoas', 'mortos', 'feridos_leves', 'feridos_graves', 'ilesos',
       'ignorados', 'feridos', 'veiculos', 'latitude', 'longitude', 'regional',
       'delegacia', 'uop'],
      dtype='object')

In [14]:
ilesa1 = sum(df1['ilesos'])
grave1 = sum(df1['feridos_graves'])
pessoas1 = sum(df1['pessoas'])
prop1_1 = ilesa1  / pessoas1
prop1_2 = grave1 / pessoas1

ilesa2 = sum(df2['ilesos'])
grave2 = sum(df2['feridos_graves'])
pessoas2 = sum(df2['pessoas'])
prop2_1 = ilesa2  / pessoas2
prop2_2 = grave2 / pessoas2

In [15]:
df = {'2019': [prop1_1, prop1_2, f'{prop1_1:.0%}', f'{prop1_2:.0%}'],
      '2020': [prop2_1, prop2_2, f'{prop2_1:.0%}', f'{prop2_2:.0%}']
     }

linha = ['Proporção ilesos','Proporção feridos graves', 'Porcentagem de ilesos','Porcentagem de feridos graves']
df = pd.DataFrame(df, index = linha)
df

                                   2019      2020
Proporção ilesos               0.422954  0.412268
Proporção feridos graves       0.114455  0.115656
Porcentagem de ilesos               42%       41%
Porcentagem de feridos graves       11%       12%

### c) mostre, reorganizando o conjunto de dados, se a pandemia conseguiu diminuir ou não a incidência de acidentes nas rodovias federais.

passo a passo:

1- Em relação a quantidade de acidentes, calculei a diferença em quantidade e porcentagem entre os anos. O método que utilizei foi verificar a quantia de linhas utilizando o len() e depois fiz as contas necessárias.

2- Em relação a quantidade de acidentes por estado, calculei a diferença em quantidade e porcentagem entre os anos. O método utilizado foi a partir do value_counts(), que conta a repetição de palavras, depois coloquei em uma lista apenas os estados em que houve redução de acidentes. Para isso tive de criar duas repetições, as quais verificaraim se o conteudo de uf 2019 é igual a uf de 2020, ja que as series de cada ano não ficaram na mesma ordem.

3- Utilizei o mesmo esquema do passo 1 para descobrir a diferença e porcentagem de pessoas e mortos.

4- Criei um dataframe em q as colunas eram as porcentagens e a diferença, as linhas as classificações de acidentes que utilizei e os estados oi país e depois coloquei nomes para as linhas.

In [16]:
acidente1 = len(df1.index)
acidente2 = len(df2.index)

diferença_acidentes = acidente1 - acidente2

porcentagem_acidentes = f'{1 - acidente2 / acidente1:.1%}'

print(diferença_acidentes)
print(porcentagem_acidentes)

3999
5.9%

In [17]:
estados1 = df1['uf'].value_counts()
estados2 = df2['uf'].value_counts()

l1_4c = []
l2_4c = []
for i in range(27):
    for j in range(27):
        if  estados1.index[i] == estados2.index[j] and estados1[i] - estados2[j] > 0:
            l1_4c.append(estados1.index[i])
            l1_4c.append(estados1[i] - estados2[j])

        if estados1.index[i] == estados2.index[j] and estados2[i] / estados1[i] < 1:
            l2_4c.append(estados1.index[i])
            l2_4c.append(f'{(1 - estados2[i] / estados1[i]):.1%}')
            
print(l1_4c)
print()
print(l2_4c)

['MG', 357, 'SC', 1211, 'PR', 540, 'RJ', 384, 'RS', 419, 'SP', 337, 'BA', 28, 'GO', 128, 'ES', 312, 'PE', 179, 'CE', 125, 'PB', 163, 'RO', 48, 'RN', 104, 'PI', 146, 'DF', 50, 'AL', 1, 'SE', 38]

['MG', '4.1%', 'SC', '14.4%', 'PR', '7.0%', 'RJ', '8.3%', 'RS', '9.1%', 'SP', '7.7%', 'BA', '0.8%', 'GO', '3.8%', 'ES', '10.0%', 'PE', '7.5%', 'CE', '7.4%', 'PB', '1.6%', 'RO', '3.1%', 'RN', '2.5%', 'MS', '7.1%', 'PI', '10.8%', 'MA', '3.3%', 'AL', '0.2%', 'SE', '2.8%']

In [18]:
pessoas1 = df1.pessoas.sum()
pessoas2 = df2.pessoas.sum()

diferença_pessoa = pessoas1 - pessoas2
porcentagem_pessoa = f'{(1 - pessoas2 / pessoas1):.1%}'

print(diferença_pessoa)
print(porcentagem_pessoa)

14801
9.1%

In [19]:
mortos1 = df1.mortos.sum()
mortos2 = df2.mortos.sum()

diferença_mortos = mortos1 - mortos2
porcentagem_mortos = f'{(1 - mortos2 / mortos1):.1%}'

print(diferença_mortos)
print(porcentagem_mortos)

46
0.9%

In [20]:
df_4c = pd.DataFrame({'Porcentagem': [porcentagem_acidentes, l2_4c[1], l2_4c[3], l2_4c[5], l2_4c[7], l2_4c[9], l2_4c[11],
                                      l2_4c[13], l2_4c[15], l2_4c[17], l2_4c[19], l2_4c[21], l2_4c[23], l2_4c[25], l2_4c[27], 
                                      l2_4c[29], l2_4c[31], l2_4c[33], porcentagem_pessoa, porcentagem_mortos],
                      
                      'Diferença': [diferença_acidentes, l1_4c[1], l1_4c[3], l1_4c[5], l1_4c[7], l1_4c[9], l1_4c[11] ,
                                      l1_4c[13], l1_4c[15], l1_4c[17], l1_4c[19], l1_4c[21], l1_4c[23], l1_4c[25], 
                                      l1_4c[27], l1_4c[29], l1_4c[31], l1_4c[33], diferença_pessoa, diferença_mortos]},
                     
                     index = [['Geral', 'Estado', 'Estado', 'Estado', 'Estado', 'Estado', 'Estado', 'Estado', 'Estado',
                               'Estado', 'Estado', 'Estado', 'Estado', 'Estado', 'Estado', 'Estado', 'Estado', 'Estado',
                               'Pessoas', 'Mortos'],
                    
                              
                              ['Brasil', l1_4c[0], l1_4c[2], l1_4c[4], l1_4c[6], l1_4c[8], l1_4c[10], l1_4c[12], l1_4c[14],
                               l1_4c[16], l1_4c[18], l1_4c[20], l1_4c[22], l1_4c[24], l1_4c[26], l1_4c[28], l1_4c[30],
                               l1_4c[32], 'Brasil', 'Brasil']])

df_4c.index.names = ['Acidentes', 'Local']
df_4c

                 Porcentagem  Diferença
Acidentes Local
Geral     Brasil        5.9%       3999
Estado    MG            4.1%        357
          SC           14.4%       1211
          PR            7.0%        540
          RJ            8.3%        384
          RS            9.1%        419
          SP            7.7%        337
          BA            0.8%         28
          GO            3.8%        128
          ES           10.0%        312
          PE            7.5%        179
          CE            7.4%        125
          PB            1.6%        163
          RO            3.1%         48
          RN            2.5%        104
          PI            7.1%        146
          DF           10.8%         50
          AL            3.3%          1
Pessoas   Brasil        9.1%      14801
Mortos    Brasil        0.9%         46

Resposta: 

Com este dataframe fica notório que a pandemia auxiliou na redução de acidentes em grande parte do Brasil. Apesar da diferença não parecer tão significativa , ainda assim é uma redução de cerca de 4000 casos em todo o Brasil. Analisando a diminuição por estado fica mais notório onde a pandemia influenciou mais nessa redução, tendo um grande impacto em Santa Catarina por exemplo.

Com esses dados levantados também se percebe que a quantidade de pessoas envolvidas em acidentes reduziu muito, apesar da porcentagem não ser tão significativa. Isto provavelmente está relacionado com o fato de menos famílias estarem viajando em conjunto, sendo as viagens mais para negócios e afins.

Ja com a quantidade de mortos a pandemia não surtiu tanto efeito, tendo sua redução em cerca de apenas 1%.